# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1345935fc1155c164f48d132cfcfbf6b23d3b630a6b036499403794759c1ee3a10ffc0eeb91e9952137332b3c13099e58fd7ddfa74021a0cde0c576e759b8aa8

test:
  secret_key_base: 7a74341f8ffb9c3519c35533085e95d79b6c77aec279994c6e9cdccc00f92568eb076e93a350cf81c46c99259af75a51bd0de426642825f9308e3eab6ed04f94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
